datasets:
  energy:
    column_mapping:
        
      numerical_features:
        - 'Visibility'
        - 'RH_5'
        - 'Windspeed'
        - 'RH_out'
      prediction:
        - 'Appliances'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/energydata_complete.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
